### ISSUE TITLE
Electronic components

### ISSUE THREAD

**Issue by ViktorDomnikov** [dekuNukem/daytripper#10]
Hello.
What Electronic components did you use in this project?
Resistors? Capacitors? etc.
I see tags C11, C12, R2, but I don't know what capacitor.
Please tell me where I can find this information.
Thank you.

**Comment by dekuNukem** [comment]
All the details are in the board and schematic files in the [pcb folder](https://github.com/dekuNukem/daytripper/tree/master/pcb). They were made using Eagle, which can be [download it here](https://www.autodesk.com/products/eagle/free-download).
