### ISSUE TITLE
About TX

### ISSUE THREAD

**Issue by oniyakun** [dekuNukem/daytripper#13]
Im already success put all components on the TX&RX board just like your's and flash the firmware via USB DFU.

RX looks working fine, the stats led first get blink and into dim, when press user button it typed out the debug messages. So far look nice.

But TX I think it had some issues, the stats led always breath and never stop, also RX did not received data from the TX. I tried press user button over 2 secs into test mode, but the led just go out, also didnt receive any data. I dont know whats wrong about Im doing, all components look got nice soldering and works good, pls help me, huge thx!

**Comment by dekuNukem** [comment]
Hi oniyakun:

I did discover an issue with the early production boards, such as the one you have.

I have [written about it here](https://github.com/dekuNukem/daytripper/blob/master/mysterious_glitch.md). Fortunately it is easily fixable, so feel free to give it a try.

I do apologise about the delay in response, I must have missed it. 

Best Regards,

Allen
