### ISSUE TITLE
Having two close by

### ISSUE THREAD

**Issue by kcc1982** [dekuNukem/daytripper#17]
I got my coworker one since I thought they were on different frequencies but it turns out we are locking each other's computers. Is there a way to have two of these in the same cube farm.

**Comment by dekuNukem** [comment]
By default all daytrippers are on the same adress, so they will trigger each other if there are more than one.

I wrote you a custom firmware that uses a different address. Flash them on one of the TX/RX pairs, and they'll talk on a different address, allowing you to use two sets at the same time without interference.

Download the firmware here:

https://cdn.discordapp.com/attachments/514708977498587148/657235124378664980/alt_addr.zip

and refer to "USB firmware updates" section of [this guide ](https://github.com/dekuNukem/daytripper/blob/master/advanced_usage.md#usb-firmware-updates) to see how to upload it.

**Comment by kcc1982** [comment]
It worked. Thank you very much

On Dec 19, 2019 10:01 AM, dekuNukem <notifications@github.com> wrote:

By default all daytrippers are on the same adress, so they will trigger each other if there are more than one.

I wrote you a custom firmware that uses a different address. Flash them on one of the TX/RX pairs, and they'll talk on a different address, allowing you to use two sets at the same time without interference.

Download the firmware here:

https://cdn.discordapp.com/attachments/514708977498587148/657235124378664980/alt_addr.zip

and refer to "USB firmware updates" section of this guide <https://github.com/dekuNukem/daytripper/blob/master/advanced_usage.md#usb-firmware-updates> to see how to upload it.
