### ISSUE TITLE
RX not receiving signal

### ISSUE THREAD

**Issue by nicolasnsuy** [dekuNukem/daytripper#21]
Hi, i been not able to use my sensors for a while both TX and RX were working fine, now the RX turn on the blue light breathing and then go dim.

The TX turns on ok and the blue light turns on when you you trigger the sensor.

The pc is not making any action and if i press de debug button on RX doesn't show receiving any package from the TX.

I already try updating the firmware but they still doing the same.

Any idea of what can be happening?

Thank you!

**Comment by dekuNukem** [comment]
Hi There! It sounds like a issue that was discovered in early-production run models. Please take a look at [this guide](https://github.com/dekuNukem/daytripper/blob/master/mysterious_glitch.md) and see if it helps. I do apologise if for the inconvience.

**Comment by nicolasnsuy** [comment]
Thank you for your response.

I already follow all steps but with out any luck, the TX has a Air gap but still not working.

Is there anything else i can try?

Thanks!

**Comment by dekuNukem** [comment]
Can you tell me your Tindie order number? I'll look into it.

**Comment by nicolasnsuy** [comment]
Sure, Order Number: 174290.

Thank you!

**Comment by dekuNukem** [comment]
Great! I'm happy to sort this one out for you. Please check your email.
