### ISSUE TITLE
Hi, I was wondering, did you print these circuit boards by yourself?

### ISSUE THREAD

**Issue by linleo10** [dekuNukem/daytripper#23]
Hi, I was wondering, did you print these circuit boards by yourself?

**Comment by dekuNukem** [comment]
For prototypes, i designed the circuit boards, had them made, and reflow soldered all the components. This went on for a few iterations until it is ready for production.

For production, I use a PCB fab house, who use professional pick-and-place machine to assemble all my boards.

**Comment by robvoi** [comment]
Didn't want to open a new issue - but have a question.

What finish do you use for your PCBs?
OSP, HASL, ENIG?

Thanks a lot
