### ISSUE TITLE
How to open the PCB files?

### ISSUE THREAD

**Issue by hiphonezhang** [dekuNukem/daytripper#6]
I use the allegro 16.6 and eagle 9.5.0，but can‘t open.

**Comment by dekuNukem** [comment]
The PCB file was made using Eagle. You can download it here:

https://www.autodesk.com/products/eagle/free-download

This project is within the limits of the free version, so you don't have to pay anything.

**Comment by hiphonezhang** [comment]
Thank you for your reply，Maybe the PCB file I downloaded is wrong，I  download it again and open it successfully.
