### ISSUE TITLE
Any plans to release the schematics/parts list?

### ISSUE THREAD

**Issue by casconed** [dekuNukem/daytripper#7]

**Comment by dekuNukem** [comment]
The schematic is the Eagle `.sch` files in the `pcb` folder, and part list can be generated from that.  Here's a tutorial:

https://www.autodesk.com/products/eagle/blog/creating-bom-pcb-manufacturing-basics-2/

**Comment by casconed** [comment]
awesome, sorry - should have taken a more comprehensive look before opening an issue!
